apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-cicd
  template:
    metadata:
      labels:
        app: flask-cicd
    spec:
      containers:
      - name: flask-cicd
        image: flask-cicd:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
