apiVersion: v1
kind: Service
metadata:
  name: flask-cicd
spec:
  selector:
    app: flask-cicd
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32500
  type: NodePort
